import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import "./favicon.ico"

// Import and configure the fonts
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

// Metadata for the page
export const metadata: Metadata = {
  title: "SDG Classroom",
  description: "Generated by create next app",
  icons: {
    icon: "./favicon.ico ",
  },
  openGraph: {
    title: 'SDG Classroom', // Open Graph title
    description: 'Classroom for SDG', // OG description
    url: '', // Your app URL
    images: [
      {
        url: '/favicon.ico', // Image for social link previews
        width: 32,
        height: 32,
        alt: 'My App Logo',
      },
    ],
  },
};

// RootLayout Component
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${geistSans.variable} ${geistMono.variable}`}>
      <body className="bg-black text-white min-h-screen">
        {/* Header */}
        <header className="flex justify-end">
          <div className="flex w-full max-w-6xl items-center justify-end px-4 py-3 sm:px-6">
            {/* <button className="rounded-full border border-blue-500/60 px-4 py-2 text-sm font-semibold text-white transition hover:bg-blue-600/80 sm:px-5 sm:py-2.5 sm:text-base">
              Sign In
            </button> */}
          </div>
        </header>

        {/* Main Content */}
        <main>{children}</main>
      </body>
    </html>
  );
}
